### ISSUE TITLE
Get email and organization name from user (hossted register)

### ISSUE THREAD

**Issue by liorkesos** [hossted/cli#1]
Wehn user runs hossted register collect his email and organization name

**Comment by liorkesos** [comment]
Maybe we can adopt stuff from here ?
https://dev.to/divrhino/building-an-interactive-cli-app-with-go-cobra-promptui-346n

**Comment by billylkc** [comment]
Should the config file under ~/.hossted/config.yaml or ~/.hossted.yaml?
It makes more sense to me to put all the config, docker compose, etc.. under the same folder (~/.hossted/)

**Comment by billylkc** [comment]
and for the config.yaml file I assume the following fields first, let me know if you've got other fields/structure.
As go is a static type language, it's better to have a somehow fixed structure first.

user: "Billy Lam"
organization: "ABC company"
