### ISSUE TITLE
 sessiontoken not saved in config

### ISSUE THREAD

**Issue by liorkesos** [hossted/cli#10]
In hossted register - make sure sessionToken is saved in config
Next commands should send it as a parameter (so we can track the user running the cli commands)

**Comment by liorkesos** [comment]
This is the command and out put we got
```
ubuntu@wikijs:~$ hossted register

No existing config file.
New config file is created  - /home/ubuntu/.hossted/config.yaml

Email: lior@linnovate.net
Organization: Linnovate
Registering user. Please wait a second.

Updated config. Registered User - [lior@linnovate.net - Linnovate]

Please visit the dashboard link -

ubuntu@wikijs:~$ cat .hossted/config.yaml
email: lior@linnovate.net
organization: Linnovate
userToken:
sessionToken:```

**Comment by liorkesos** [comment]
<div style="position: relative; padding-bottom: 56.25%; height: 0;"><iframe src="https://www.loom.com/embed/86887b409e234024afea30a9750f5c01" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></iframe></div>

**Comment by liorkesos** [comment]
https://www.loom.com/share/86887b409e234024afea30a9750f5c01

**Comment by billylkc** [comment]
Fixed issue in dev. The root cause is if the email/organization is being registered before, the program didnt handle the case.
Added checking to see if the sessionToken is empty from the register API. Also the fields JWT and Endpoint in response struct needs to be exposed.

**Comment by liorkesos** [comment]
Confirmed that its' fixed in dev.
