### ISSUE TITLE
Missing Config File after hossted activate -t compose

### ISSUE THREAD

**Issue by Alina990612** [hossted/cli#148]
When we run the command "hossted activate -t compose" it looks in home directory but it should look in the app directory. 

<img width="1269" alt="image" src="https://github.com/user-attachments/assets/5a518f30-5c4c-45d6-b641-4150e7c8900d">

**Comment by AdheipSingh** [comment]
this actually config file not compose file. IMHO a lot of jargon init msg have cleaned up here https://github.com/hossted/cli/pull/156 so should be good.

**Comment by liorkesos** [comment]
confirmed as  fixed
