### ISSUE TITLE
lock / unlock master key access

### ISSUE THREAD

**Issue by niryariv** [hossted/cli#17]
Consider having a built in time limit - ie the server auto-locks again after a certain # of hours

**Comment by liorkesos** [comment]
command: *hossted set remote-support false|true*  
folder: /root  

To enable or disable remote ssh access with our maintanece and support key - Insert or remove a comment if you match the public key
key: ```AAAB3NzaC1yc2EAAAADAQABAAABAQCXfKWaimQKigm7A8mxqoEr2e2OOBxpBMvYu8BmMuP2+GEU3FP2CHnVUAPlQ7ByniW+Qg7xlDLQa9kb+5X3r2bwnN7FkEzD3fF/qbfJHjdFlPGN+tdkkoSZzfzsa/z3F4H7wI5pz48cZryph8/dKlrG92GF05womLrFUQyHPbuyMYqGoXTMIaXYaWQm84BndMu+cvqas25YOLyYQXT50BrcWNF24+aqo6H9upmRMN+R1KN0pHxV+5jPDOyZj8PiAAVWCAM574mSm/R8jKZ0qdyMcUL0uThIBtDbMXhgfJn3NdD/3x/DxNnXy84WIHPpY5OPzU3miuVMkNpD8QZRLTFX
```

**Comment by billylkc** [comment]
Implemented in dev, should be available in 0.1.6

**Comment by niryariv** [comment]
After running `hossted set remote-support false` I see a line commented in `/root/.ssh/authorized_keys` but I can still log in with the master key. Should we update ssh of the change in some way for this to work? cc @liorkesos
