### ISSUE TITLE
Enable command execution for non-registered users

### ISSUE THREAD

**Issue by niryariv** [hossted/cli#20]
Currently it seems like we force the user to register in order to run httpopen etc:

<img width="529" alt="Screen Shot 2022-04-13 at 16 06 27" src="https://user-images.githubusercontent.com/1771/163186702-c8f54863-188e-4c21-a3da-1f1711e3f150.png">

 That's not our intention - we want the users to register, but we don't force them to. They should be able to run any command without registering. cc @liorkesos

**Comment by billylkc** [comment]
Please confirm.

**Comment by liorkesos** [comment]
@niryariv is accurate here. we do not require register in order to run basic commands (like ps / logs / app-commands)

**Comment by billylkc** [comment]
Probably need to discuss more on this, coz there is some JWT/Session token returned from the register command, if we allow the unregistered user to use the cli, need more clarifications on how and when to communicate with other server side APIs (future).

Lets discuss more in next meeting.

**Comment by niryariv** [comment]
@billylkc can you explain the concern here?

**Comment by niryariv** [comment]
@billylkc if the issue's fixed please comment and assign to me, so I can test - this way I can keep track of what I need to check in each release. Thanks :)
