### ISSUE TITLE
Multi environment support

### ISSUE THREAD

**Issue by liorkesos** [hossted/cli#21]
We need to interact with different API environments based on the branch that was built in the [request](https://github.com/hossted/cli/blob/94fdc1b89e8e0d669c91b8fa3c7ef39d1d8a8d06/hossted/register.go#L79) but possibly in additional place
main: https://app.hossted.com/api/register
dev:  https://app.dev.hossted.com/api/register

**Comment by billylkc** [comment]
Implemented in dev, should be available in 0.1.6.
Need end to end testing with backend side.
