### ISSUE TITLE
Hanndle auth removal where not applicable

### ISSUE THREAD

**Issue by niryariv** [hossted/cli#23]
when the user attempts bauth removal, check if bauth is implemented. if not, display "Basic Authentication not implemented in this app"

**Comment by niryariv** [comment]
@liorkesos is it possible to check as the user attempts the command whether this is applicable or not?

**Comment by billylkc** [comment]
Please list some general commands for apps as reference

**Comment by niryariv** [comment]
As we discussed, this can be checked on the fly, no need to keep a list of where it's applicable

**Comment by billylkc** [comment]
is the current command **hossted httpopen**? 
if yes, please refer to #15, on how the reverse command should be done.

**Comment by niryariv** [comment]
yes, current command is httpopen
