### ISSUE TITLE
New text when user runs "hossted" with no command

### ISSUE THREAD

**Issue by niryariv** [hossted/cli#28]
replace `A brief description of your application` with `Hossted CLI v0.1.7 - for help contact us at support@hossted.com` ("v0.1.7" should contain the actual version of course)

**Comment by billylkc** [comment]
Should be fixed in v0.1.8. Will reassign when it is released.

**Comment by billylkc** [comment]
Implemented in 0.1.8, please check

**Comment by niryariv** [comment]
confirmed to work, closing.
