### ISSUE TITLE
Command list (General Available/App Specific)

### ISSUE THREAD

**Issue by billylkc** [hossted/cli#31]
@niryariv Feels like a lot of discussion/bugs involves whether the commands are GA or app specifics.
Please help to provide a list of the general available commands as discussed before.

Here is the list I currently maintained (as of 0.1.7). Feel free to edit.

**_General available_**
- set auth
- set remote support

**_App specific_**
- Set domain (All except gitbucket)
- httpopen (gitbucket)

**Comment by niryariv** [comment]
`set auth` is globally available, but in some case not applicable (the app doesn't have basic auth enabled). We'd still consider it a generic commands, though, just inform the user whenever running it doesn't have any effect.

`set domain` should be generic, I'm not clear on the issue there - we'll continue discussing in #7 

`httpopen` is basically just a synonym for `set auth false`. It's there for legacy reasons and we might just remove it altoghether - @liorkesos what do you think?

**Comment by billylkc** [comment]
For the latest command mapping list, please refer to the first few lines under the **./hossted/commands.go** file
