### ISSUE TITLE
support /opt/hossted in addition to /opt/linnovate

### ISSUE THREAD

**Issue by niryariv** [hossted/cli#42]
```
ubuntu@rocket:~$ hossted set auth false
Can not open /opt/linnovate/run/software.txt. Please check.
open /opt/linnovate/run/software.txt: no such file or directory
```

We're changing the directory from `/opt/linnovate` to `/opt/hossted.` we should continue supporting the former, though, to maintain backwards compatibility. so, the CLI needs to check which one exists and work with that. Please give this high priority.

**Comment by billylkc** [comment]
Is the file content /opt/hossted/run/software.txt or /opt/linnovate/run/software.txt going to be changed accordingly as well?
It has to be in this pattern now, Linnovate-AWS-wikijs.

Please let me know if the content would be changed to Hossted-AWS-wikijs as well.

**Comment by niryariv** [comment]
We're just changing the name of the directory from /opt/linnovate to /opt/hossted, everything under the dir remains as is.

we're not necessarily changing to Hossted-AWS-wikijs but it would be good if your code would be able to support it alongside the current format, same as we do for the dir names
