### ISSUE TITLE
hossted set monitoring true/false

### ISSUE THREAD

**Issue by liorkesos** [hossted/cli#45]
We want to setup a command that will toggle monitoring
What it will do is show or remove services that start with hossted-monitoring
The format will look like this...
![image](https://user-images.githubusercontent.com/245027/176437126-ae340918-849e-4912-a74e-f21f0c477d97.png)

**Comment by billylkc** [comment]
I am expecting these three lines are available (and in this order) in the docker-compose file for the parser to work
# HOSSTED APP
# HOSSTED WRAPPER
# HOSSTED WRAPPER END
