### ISSUE TITLE
register app (in config)

### ISSUE THREAD

**Issue by liorkesos** [hossted/cli#5]
When running hossted register , make sure that you save to the config the name (based on software.txt) and the location of the application
This "app registry" will the basis to app based commands (like hossted logs appName or hossted ps AppNAme)
It will also serve as the registry for the hossted ls command

**Comment by billylkc** [comment]
Merge to dev branch. Now the application info will be extracted from /opt/linnovate/run/software.txt. (assume single line, and in Linnovate-AWS-wikijs format). 
And saved to the config file as well, with the field appName, appPath
